# Generated by Django 5.1 on 2025-11-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="image",
        ),
        migrations.AddField(
            model_name="course",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="course_files/"),
        ),
    ]
