# Generated by Django 5.1 on 2025-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_course_image_course_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
